exclude:
  - .github
  - .gitignore
  - circle.yml
  - README.md
  - doc-templates

liquid:
  error_mode: strict

markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

url: https://developers.cloud-elements.com

gems:
  - jekyll-redirect-from
  - jekyll-youtube

theme: jekyll-theme-cayman